config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:edit, :update, :create, :destroy]
  end

  resources :friendships, only: [:create, :destroy]
  resources :invitations, only: [:new, :create, :destroy]

  devise_for :users
  resources :users, only: [:show]
  resources :profiles, except: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: "User"
  belongs_to :post
  validates :body, presence: true
  validates :post_id, presence: true
  validates :author_id, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]
  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.build(comment_params)
      @comment.author = current_user

      @comment.save
      redirect_to @post
    end

    def destroy
      @comment.destroy

      redirect_to @post
    end

    private
    def comment_params
      params.require(:comment).permit(:post_id, :user_id, :body)
    end

    def set_comment
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment bg-light rounded mb-3 mt-3 p-2" id="<%= dom_id comment %>">
    <div class="d-flex justify-content-between border-bottom">
        <div class="w-75">
            <div class="float-start h-100 d-flex align-items-center me-1" ><%= image_tag(comment.author.profile_picture_path, class:"rounded-circle", size: "30x30") %></div>
            <div> <%= link_to comment.author.email, comment.author, class: "fw-bold", data: { turbo_frame: "_top" } %> </div>
            <div class="text-muted"> 
                <%= comment.created_at %> 
                <% if comment.created_at != comment.updated_at %>
                    | (<%= comment.updated_at %>)
                <% end %>
            </div>
        </div>
        <% if current_user == comment.author || comment.post.author == current_user %>
            <div>
                <div class="dropdown">
                    <a href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                        <span class="bi-three-dots fs-5"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuLink">
                        <li> <%= link_to "Edit", edit_post_comment_path(comment.post, comment), class: "dropdown-item" %> </li>
                        <li> <%= button_to "Delete", post_comment_path(comment.post, comment), method: :delete, class: "dropdown-item", data: { turbo_frame: "comments"} %> </li>
                    </ul>
                </div>
            </div>
        <% end %>
    </div>
    <div class="pb-2 pt-2"> 
        <%= comment.body %> 
    </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [post, post.comments.build], method: :post, class: "d-flex align-items-center m-2") do |form| %>
  <%= form.text_area :body, placeholder: "Write your comment here", class: "w-100 border rounded" %>
  <button type="submit" class="btn btn-secondary bi-arrow-down m-1" ></button>
  <span id="<%= dom_id post %>_comments_count" class="post-comments-count text-muted"><%= post.comments.count %></span>
<% end %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag @comment do %>
    <%= form_with(model: [@post, @comment], class: "d-flex align-items-center m-2") do |form| %>
        <%= form.text_area :body, value: @comment.body, class: "w-100 border rounded" %>
        <button type="submit" class="btn btn-secondary m-1" >Edit</button>
    <% end %>
<% end %>