config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:edit, :update, :create, :destroy]
  end

  resources :friendships, only: [:create, :destroy]
  resources :invitations, only: [:new, :create, :destroy]

  devise_for :users
  resources :users, only: [:show]
  resources :profiles, except: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  require 'open-uri'

  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_one :profile

  has_many :posts, dependent: :destroy, foreign_key: :author_id

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy, foreign_key: :author_id

  has_many :invites, 
    class_name: "Invitation", 
    foreign_key: :inviter_id, 
    dependent: :destroy
  has_many :invitees, through: :invites

  has_many :invites_received, 
    class_name: "Invitation", 
    foreign_key: :invitee_id, 
    dependent: :destroy
  has_many :inviters, through: :invites_received

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  def remove_friend(friend)
    self.friends.destroy(friend)
  end

  def profile_picture_path
    if self.profile == nil || self.profile.photo_attachment == nil
      "default-picture.jpg"
    else
      self.profile.photo
    end
  end

  def self.from_omniauth(auth)
    user = find_by(provider: auth.provider, uid: auth.uid)
    if user.nil?
      user = new(email: auth.info.email, password: Devise.friendly_token[0, 20], provider: auth.provider, uid: auth.uid)
      user.skip_confirmation!
      user.save!

      user.create_profile
      photo = URI.open(auth.info.image)
      user.profile.photo.attach(io: photo, filename: auth.info.image)
    end
    user
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
    skip_before_action :verify_authenticity_token, only: :facebook

    def facebook
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env["omniauth.auth"])

        if @user.persisted?
            sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
            set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
        else
            session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
            redirect_to new_user_registration_url
        end
    end

    def failure
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friends.html.erb
<h5 class="text-warning">Friends: </h5>
<% if current_user.friends.empty? %>
    <p class="text-muted">no friends. lol</p>
<% else %>
    <ul class="list-group">
        <% current_user.friendships.each do |friendship| %>
            <li class="list-group-item miniature-event m-1">
                <p class="text-muted">Friend</p>
                <%= link_to friendship.friend.email, friendship.friend %>
                <%= button_to "Unfriend", friendship_path(friendship.id), method: :delete %>
            </li>
        <% end %>
    </ul>
<% end %>

app/views/users/_invites_received.html.erb
<div class="invites-received mt-4">
    <h5 class="text-warning">Invites received: </h5>
    <% if current_user.invites_received.empty? %>
        <p class="text-muted">Empty!</p>
    <% else %>
        <ul class="list-group">
            <% current_user.invites_received.each do |invite| %>
                <li class="list-group-item miniature-event m-1">
                    <p class="text-muted">Received</p>
                    <%= link_to invite.inviter.email, invite.inviter  %>
                    <%= button_to "Accept Invite", friendships_path(friend_id: invite.inviter_id), :method => :post, class: "btn btn-dark m-2" %>
                </li>
            <% end %>
        </ul>
    <% end %>
</div>

app/views/users/_invites_sent.html.erb
<div class="invites-received mt-4">
    <h5 class="text-warning">Invites sent: </h5>
    <% if current_user.invites.empty? || current_user.invites.first.id == nil %>
        <p class="text-muted">None!</p>
    <% else %>
        <ul class="list-group">
            <% current_user.invites.each do |invite| %>
                <% next if invite.id == nil %>
                <li class="list-group-item miniature-event m-1">
                    <p class="text-muted">Sent</p>
                    <%= link_to invite.invitee.email, invite.invitee  %>
                    <%= button_to "Cancel Invite", invitation_path(invite.id), :method => :delete, class: "btn btn-dark m-2" %>
                </li>
            <% end %>
        </ul>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="m-3">
    <div class="card shadow">
        <div class="card-img d-flex justify-content-center">
            <%= image_tag(@user.profile_picture_path, class:"rounded-circle mt-3", size: "400x400") %>
        </div>
        <div class="card-body text-center">
            <% if current_user.friends.include?(@user) %>
                <% friendship = current_user.friendships.find_by(friend: @user) %>
                <%= button_to "Unfriend", friendship_path(friendship.id), class:"btn btn-danger m-3", method: :delete %>
            <% elsif current_user.invitees.include?(@user) %>
                <% invite = current_user.invites.find_by(invitee: @user) %>
                <%= button_to "Cancel Invite", invitation_path(invite.id), class: "btn btn-danger m-3", method: :delete %>
            <% elsif @user.invitees.include?(current_user) %>
                <% invite = @user.invites.find_by(invitee: current_user) %>
                <%= button_to "Accept Invite", friendships_path(friend_id: invite.inviter_id), class: "m-3 btn btn-success", method: :post %>
            <% elsif current_user == @user %>
                <p class="text-muted">This is you!</p>
            <% else %>
                <%= button_to "Invite to friends", invitations_path(inviter_id: current_user.id, invitee_id: @user.id), class: "btn btn-dark m-3" %>
            <% end %>
            <h2 class="card-title"> <%= @user.email %> </h2>
        </div>

        <% unless (!@user.profile && current_user != @user) %>
            <div class="m-2">
                <div class="text-center">
                    <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseProfile" aria-expanded="false" aria-controls="collapseProfile">
                        Toggle Profile Info
                    </button>
                </div>
                <div class="collapse" id="collapseProfile"">
                    <% if @user.profile %>
                        <%= turbo_frame_tag "user_profile", src: @user.profile %>
                    <% else %>
                        <%= turbo_frame_tag "user_profile", src: new_profile_path %>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>
    
    <% if @user.posts.empty? %>
        <p class="text-center">This user has no activity.</p>
    <% else %>
        <%= render "posts/posts", posts: @user.posts %>
    <% end %>
</div>