config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:edit, :update, :create, :destroy]
  end

  resources :friendships, only: [:create, :destroy]
  resources :invitations, only: [:new, :create, :destroy]

  devise_for :users
  resources :users, only: [:show]
  resources :profiles, except: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: "User"
  belongs_to :post
  validates :body, presence: true
  validates :post_id, presence: true
  validates :author_id, presence: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  after_create :create_inverse_relationship
  after_destroy :destroy_inverse_relationship

  belongs_to :user
  belongs_to :friend, class_name: "User"

  validates :user, presence: true
  validates :friend, presence: true, uniqueness: { scope: :user }
  validate :not_self

  private

  def create_inverse_relationship
    friend.friendships.create(friend: user)
  end

  def destroy_inverse_relationship
    friendship = friend.friendships.find_by(friend: user)
    friendship.destroy if friendship
  end

  def not_self
    errors.add(:friend, "can't be equal to user") if user == friend
  end
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :invitee, class_name: "User"
  belongs_to :inviter, class_name: "User"

  validates :inviter, presence: true
  validates :invitee, presence: true, uniqueness: { scope: :inviter }

  validate :not_friends
  validate :not_pending
  validate :not_self

  def accept
    inviter.friends << invitee
    destroy
  end

  def reject
    destroy
  end

  private

  def not_self
    errors.add(:invitee, "can't be equal to inviter") if inviter == invitee
  end

  def not_friends
    errors.add(:invitee, 'is already added') if inviter.friends.include?(invitee)
  end

  def not_pending
    errors.add(:invitee, 'already requested friendship') if invitee.invitees.include?(inviter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :post_id, uniqueness: { scope: :user_id }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: "User"
  has_one_attached :photo

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  validates_presence_of :gender, :location, :phone_number, :birth_date
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  require 'open-uri'

  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_one :profile

  has_many :posts, dependent: :destroy, foreign_key: :author_id

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy, foreign_key: :author_id

  has_many :invites, 
    class_name: "Invitation", 
    foreign_key: :inviter_id, 
    dependent: :destroy
  has_many :invitees, through: :invites

  has_many :invites_received, 
    class_name: "Invitation", 
    foreign_key: :invitee_id, 
    dependent: :destroy
  has_many :inviters, through: :invites_received

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  def remove_friend(friend)
    self.friends.destroy(friend)
  end

  def profile_picture_path
    if self.profile == nil || self.profile.photo_attachment == nil
      "default-picture.jpg"
    else
      self.profile.photo
    end
  end

  def self.from_omniauth(auth)
    user = find_by(provider: auth.provider, uid: auth.uid)
    if user.nil?
      user = new(email: auth.info.email, password: Devise.friendly_token[0, 20], provider: auth.provider, uid: auth.uid)
      user.skip_confirmation!
      user.save!

      user.create_profile
      photo = URI.open(auth.info.image)
      user.profile.photo.attach(io: photo, filename: auth.info.image)
    end
    user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]
  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.build(comment_params)
      @comment.author = current_user

      @comment.save
      redirect_to @post
    end

    def destroy
      @comment.destroy

      redirect_to @post
    end

    private
    def comment_params
      params.require(:comment).permit(:post_id, :user_id, :body)
    end

    def set_comment
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @post = Post.find(params[:post_id])
        @like = @post.likes.build
        @like.user = current_user

        @like.save
        redirect_to @post
    end

    def destroy
      @post = Post.find(params[:post_id])
      @like = @post.likes.find(params[:id])
      @like.destroy

      redirect_to @post
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    def index
        friends_ids = current_user.friends.pluck(:id)
        friends_posts = []
        Post.all.each { |post| friends_posts << post if friends_ids.any? { |id| id == post.author_id } }
        @posts = current_user.posts + friends_posts
    end

    def show
    end

    def new
        @post = current_user.posts.build
    end

    def create
        @post = current_user.posts.build(post_params)

        respond_to do |format|
            if @post.save
                @post.photo.attach(params[:post][:photo])
                format.turbo_stream
            else
                format.html { render :new, status: :unprocessable_entity }
            end
        end 
    end

    def edit
    end

    def update
        if @post.update(post_params)
            @post.photo.attach(params[:post][:photo]) unless params[:post][:photo].nil?
            redirect_to @post
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @post.destroy

        respond_to { |format| format.turbo_stream }
    end

    private
    def post_params
        params.require(:post).permit(:body)
    end

    def set_post
        @post = Post.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinConnect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light rounded shadow-sm sticky-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="<%= root_path %>">
          <%= image_tag("odin-connect.png", size: "40x40", class: "rounded") %>
          OdinConnect
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Home", root_path, class: "nav-link"%>
            </li>

            <li class="nav-item">
              <%= link_to "Invite someone", new_invitation_path, class: "nav-link" %>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Invites sent
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <% if current_user.invites.empty? || current_user.invites.first.id == nil %>
                  <li class="dropdown-item">No invites sent</li>
                <% else %>
                  <% current_user.invites.each do |invite| %>
                    <% next if invite.id == nil %>
                    <li class="dropdown-item d-flex align-items-center justify-content-between"> 
                      <%= link_to invite.invitee.email, invite.invitee %>
                      <%= button_to "Cancel", invitation_path(invite.id), method: :delete, class: "m-3 btn btn-danger" %>
                    </li>
                  <% end %>
                <% end %>
              </ul>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Invites received
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <% if current_user.invites_received.empty? %>
                  <li class="dropdown-item">No invites received</li>
                <% else %>
                  <% current_user.invites_received.each do |invite| %>
                    <li class="dropdown-item d-flex align-items-center justify-content-between"> 
                      <%= link_to invite.inviter.email, invite.inviter %>
                      <%= button_to "Accept", friendships_path(friend_id: invite.inviter_id), method: :post, class: "m-3 btn btn-success" %>
                    </li>
                  <% end %>
                <% end %>
              </ul>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Friends list
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <% if current_user.friends.empty? %>
                  <li class="dropdown-item">No friends found</li>
                <% else %>
                  <% current_user.friendships.each do |friendship| %>
                    <li class="dropdown-item d-flex align-items-center justify-content-between"> 
                      <%= link_to friendship.friend.email, friendship.friend %>
                      <%= button_to "Unfriend", friendship_path(friendship.id), method: :delete, class: "m-3 btn btn-danger" %>
                    </li>
                  <% end %>
                <% end %>
              </ul>
            </li>
          </ul>

          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to current_user.email, current_user, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Settings", edit_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign out", destroy_user_session_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
    <div class="sticky-bottom">
        <% flash.each do |type, msg| %>
          <div class="p-3 mt-3 bg-light shadow-sm small rounded text-center">
              <%= msg %>
          </div>
        <% end %>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinConnect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="vh-100">
    <div class="h-100 d-flex justify-content-evenly">
      <div class="d-flex align-items-center">
        <%= image_tag("odin-connect.png", size: "300x300") %>
        <span class="logo">OdinConnect</span>
      </div>
      <div class="d-flex flex-column justify-content-center fs-5">
        <div>
            <% flash.each do |type, msg| %>
                <div class="p-3 m-3 bg-light shadow-sm rounded small text-center">
                    <%= msg %>
                </div>
            <% end %>
        </div>
        <%= yield %>
      </div>
    </div>
  </body>
</html>